### PR TITLE
Initial hardware-only 2018 support

### LINKED ISSUE #1: Add type checking for HAL interface
Will help catch errors for users.

I'm thinking the best way to go about this is with a decorator that uses the dynamically generated eval stuff found in hal-sim.

### LINKED ISSUE #4: Implement new motion magic stuff
> CANTalonSRX.h has the parameter values. The two eMotMag_ flags. You have to use the scaleVelocityToNativeUnits function on the inputs and then use setParameter to send the value.

### LINKED ISSUE #9: Add closed loop voltage functions
`setNominalClosedLoopVoltage` function, motor voltage to output when closed loop features are being used
`disableNominalClosedLoopVoltage` function, disables the nominal closed loop voltage compensation.
`getNominalClosedLoopVoltage` function, returns the currently selected nominal closed loop voltage.

### LINKED ISSUE #10: Add setClosedLoopOutputDirection function
`setClosedLoopOutputDirection` function, output direction in a closed loop scenario, either true or false

### LINKED ISSUE #11: Add setSensorDirection function
`setSensorDirection` function, either true or false to reverse sensor direction

### LINKED ISSUE #12: Rewrite to support new CTRE drivers
CTRE told me during the 2017 season that they were exploring an approach that would make it easier to create a third-party wrapper around their drivers. I anticipate that a small rewrite of this package will be necessary -- but it should be fairly straightforward to do.

I've reached out to them about the status of the new drivers.

### LINKED ISSUE #13: Add support for the Pigeon IMU
Depends on #12

### LINKED ISSUE #17: Add support for the Victor SPX
Depends on #12

### PR DESCRIPTION
**Pull request by virtuald**
I don't have hardware, so I can't confirm that this actually works. If someone can confirm that it works on hardware, I'll push an initial release so that people can start using it.

* Fixes #1
* Fixes #4 (well... once CTRE re-releases it?)
* Fixes #9
* Fixes #10
* Fixes #11
* Fixes #12
* Fixes #13
* Fixes #17

Here's an initial compiled wheel that I've installed on a RoboRIO and it doesn't seem to crash -- download the file to the RoboRIO, and execute 'pip3 install filename.whl'. The final release will be in opkg form.

https://www.tortall.net/~robotpy/feeds/2018-dev/robotpy_ctre-2017.0.3.post0.dev17-cp36-cp36m-linux_armv7l.whl

**Note**: Simulation still does not work

### CODE REVIEW

**Comment by ErikBoesen** [comment]
@twinters007 Sure

**Comment by virtuald** [comment]
@auscompgeek why did you add the `autogen/__init__.py` to git? When I run python setup.py sdist locally when the directory doesn't exist, it includes the autogen in the sdist...

**Comment by auscompgeek** [comment]
@virtuald It includes the C++ parts in the sdist, but not the Python files. (Take a look at the Travis CI logs.)

**Comment by virtuald** [comment]
When I run it locally:

```
...
copying ctre/_impl/autogen/CANifier.hpp -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/MotController.cpp.inc -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/MotController.hpp -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/PigeonIMU.cpp.inc -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/PigeonIMU.hpp -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/__init__.py -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/canifier_sim.py -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/ctre_enums.cpp.inc -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/ctre_sim_enums.py -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/motcontroller_sim.py -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
copying ctre/_impl/autogen/pigeonimu_sim.py -> robotpy-ctre-2017.0.3.post0.dev23/ctre/_impl/autogen
...
```

**Comment by auscompgeek** [comment]
Hm, yeah. I had trouble reproducing that issue on my laptop (with setuptools 38.2.4), but I was able to reproduce this on someone else's Ubuntu installation. I wonder what version of setuptools is on Travis CI.

**Pull request merged**
