### PR TITLE
Update CTRE libraries

### LINKED ISSUE #145: [nag] Update Maven Dependencies
Maven library updates available:

- api-cpp: 5.20.2 --> 5.21.1
- api-cpp-sim: 5.20.2 --> 5.21.1
- cci: 5.20.2 --> 5.21.1
- cci-sim: 5.20.2 --> 5.21.1
- simCANCoder: 5.20.2 --> 5.21.1
- simPigeonIMU: 5.20.2 --> 5.21.1
- simTalonFX: 5.20.2 --> 5.21.1
- simTalonSRX: 5.20.2 --> 5.21.1
- simVictorSPX: 5.20.2 --> 5.21.1
- wpiapi-cpp: 5.20.2 --> 5.21.1
- wpiapi-cpp-sim: 5.20.2 --> 5.21.1

### PR DESCRIPTION
**Pull request by virtuald**
- Fixes #145

### CODE REVIEW

**Comment by auscompgeek** [comment]
Hmm, I'm surprised we don't use `py::overload_cast`.

**Comment by virtuald** [comment]
I did at first, but it fails in certain cases that I no longer remember.

**Comment by virtuald** [comment]
Let's not merge until we see CTRE announce this, or that the library shows up on https://maven.ctr-electronics.com/release/com/ctre/phoenix/Phoenix-frc2022-latest.json, just in case there's an issue.

**Comment by auscompgeek** [comment]
... or it shows up on https://github.com/CrossTheRoadElec/Phoenix-Releases/releases

**Comment by auscompgeek** [comment]
Just got the GitHub notification from CTRE. Good to go?

**Comment by virtuald** [comment]
:shipit:

**Pull request merged**
